# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kngk-portal
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "kngk-portal"
fullnameOverride: "kngk-portal"

service:
  type: LoadBalancer
  port: 4000
  targetPort: 4000
  nodePort: 30300
  externalIPs:
    - 10.10.5.70
    - 10.10.5.71

tls:
  enabled: false

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kngk-portal.default.svc.cluster.local
      paths: []

  tls: []
  #  - secretNamls e: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Liveness and Readiness probe values.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
