stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2

prepare:
  image: node:13
  stage: build
  cache:
    key: "${CI_COMMIT_REF_SLUG}-build"
    paths:
      - node_modules/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=true

build_development:
  image: node:13
  stage: build
  environment:
    name: development
  cache:
    key: "${CI_COMMIT_REF_SLUG}-development"
    paths:
      - node_modules/
      - apps/portal/.next/cache/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=false
    - cd apps/portal && npx next telemetry status && npx next telemetry disable && cd ../..
    - ./entrypoint.sh test -u || true
    - time yarn build
    - time yarn build:sync
    - time yarn build:syncJob
  artifacts:
    paths:
      - .next/
      - dist

build_production:
  image: node:13
  stage: build
  environment:
    name: production
  cache:
    key: "${CI_COMMIT_REF_SLUG}-production"
    paths:
      - node_modules/
      - apps/portal/.next/cache/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=false
    - cd apps/portal && npx next telemetry status && npx next telemetry disable && cd ../..
    - ./entrypoint.sh test -u || true
    - time yarn build
    - time yarn build:sync
    - time yarn build:syncJob
  artifacts:
    paths:
      - .next/
      - dist

docker:
  image: docker:latest
  stage: docker
  cache:
    key: "${CI_COMMIT_REF_SLUG}-build"
    paths:
      - node_modules/
    policy: pull
  before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY
  script:
    - env
    - |
      \
      if [ ! -d "node_modules" ]; then echo '!! CACHE NOT EXIST !!'; exit SIGINT; fi
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

helm_development:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  environment:
    name: development
  dependencies: []
  allow_failure: false
  script:
    - env
    - echo "Kubectl version" && kubectl version
    - echo "Helm version" && helm version
    # Portal
    - |
      helm upgrade ${CI_PROJECT_NAME} helm/portal \
        --set replicaCount="1" \
        --set service.nodePort="30400" \
        --set service.nodePort_debug="30401" \
        --set PORT="${PORT}" \
        --set PORT_SSL="${PORT_SSL}" \
        --set DOMAIN="${DOMAIN}" \
        --set LOGLEVEL="${LOGLEVEL}" \
        --set DATABASE_URI="${DATABASE_URI}" \
        --set DATABASE_URI_RD="${DATABASE_URI_RD}" \
        --set DATABASE_SCHEMA="${DATABASE_SCHEMA}" \
        --set DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}" \
        --set DATABASE_DROP_SCHEMA="${DATABASE_DROP_SCHEMA}" \
        --set DATABASE_MIGRATIONS_RUN="${DATABASE_MIGRATIONS_RUN}" \
        --set DATABASE_LOGGING="${DATABASE_LOGGING}" \
        --set DATABASE_REDIS_URI="${DATABASE_REDIS_URI}" \
        --set DATABASE_REDIS_TTL="${DATABASE_REDIS_TTL}" \
        --set HTTP_REDIS_URI="${HTTP_REDIS_URI}" \
        --set HTTP_REDIS_TTL="${HTTP_REDIS_TTL}" \
        --set HTTP_REDIS_MAX_OBJECTS="${HTTP_REDIS_MAX_OBJECTS}" \
        --set SESSION_NAME="${SESSION_NAME}" \
        --set SESSION_REDIS_URI="${SESSION_REDIS_URI}" \
        --set SESSION_COOKIE_TTL="${SESSION_COOKIE_TTL}" \
        --set SESSION_SECRET="${SESSION_SECRET}" \
        --set LDAP_URL="${LDAP_URL}" \
        --set LDAP_BIND_DN="${LDAP_BIND_DN}" \
        --set LDAP_BIND_PW="${LDAP_BIND_PW}" \
        --set LDAP_SEARCH_BASE="${LDAP_SEARCH_BASE}" \
        --set LDAP_SEARCH_FILTER="${LDAP_SEARCH_FILTER}" \
        --set LDAP_SEARCH_GROUP="${LDAP_SEARCH_GROUP}" \
        --set LDAP_SEARCH_BASE_ALL_USERS="${LDAP_SEARCH_BASE_ALL_USERS}" \
        --set LDAP_SEARCH_FILTER_ALL_USERS="${LDAP_SEARCH_FILTER_ALL_USERS}" \
        --set LDAP_REDIS_URI="${LDAP_REDIS_URI}" \
        --set LDAP_REDIS_TTL="${LDAP_REDIS_TTL}" \
        --set MICROSERVICE_URL="${MICROSERVICE_URL}" \
        --set SOAP_URL="${SOAP_URL}" \
        --set SOAP_DOMAIN="${SOAP_DOMAIN}" \
        --set NEWS_URL="${NEWS_URL}" \
        --set NEWS_API_URL="${NEWS_API_URL}" \
        --set MAIL_URL="${MAIL_URL}" \
        --set MAIL_LOGIN_URL="${MAIL_LOGIN_URL}" \
        --set MEETING_URL="${MEETING_URL}" \
        --set image.repository="${CI_REGISTRY_IMAGE}" \
        --set image.tag="${CI_COMMIT_SHA}" \
        --install --namespace=${KUBE_NAMESPACE} \
        --debug --values helm/portal/values.yaml
    # Portal-sync
    - |
      helm upgrade ${CI_PROJECT_NAME}-sync helm/portal-sync \
        --install --namespace=${KUBE_NAMESPACE} \
        --debug --values helm/portal-sync/values.yaml \
        --set replicaCount="1" \
        --set PORT="${PORT_MICROSERVICE}" \
        --set image.repository="${CI_REGISTRY_IMAGE}" \
        --set image.tag="${CI_COMMIT_SHA}"

helm_production:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  environment:
    name: production
  dependencies: []
  when: manual
  allow_failure: false
  script:
    - env
    - echo "Kubectl version" && kubectl version
    - echo "Helm version" && helm version
    # Portal
    - |
      helm upgrade ${CI_PROJECT_NAME} helm/portal \
        --set service.nodePort="30300" \
        --set service.nodePort_debug="30301" \
        --set PORT="${PORT}" \
        --set PORT_SSL="${PORT_SSL}" \
        --set DOMAIN="${DOMAIN}" \
        --set LOGLEVEL="${LOGLEVEL}" \
        --set DATABASE_URI="${DATABASE_URI}" \
        --set DATABASE_URI_RD="${DATABASE_URI_RD}" \
        --set DATABASE_SCHEMA="${DATABASE_SCHEMA}" \
        --set DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}" \
        --set DATABASE_DROP_SCHEMA="${DATABASE_DROP_SCHEMA}" \
        --set DATABASE_MIGRATIONS_RUN="${DATABASE_MIGRATIONS_RUN}" \
        --set DATABASE_LOGGING="${DATABASE_LOGGING}" \
        --set DATABASE_REDIS_URI="${DATABASE_REDIS_URI}" \
        --set DATABASE_REDIS_TTL="${DATABASE_REDIS_TTL}" \
        --set HTTP_REDIS_URI="${HTTP_REDIS_URI}" \
        --set HTTP_REDIS_TTL="${HTTP_REDIS_TTL}" \
        --set HTTP_REDIS_MAX_OBJECTS="${HTTP_REDIS_MAX_OBJECTS}" \
        --set SESSION_NAME="${SESSION_NAME}" \
        --set SESSION_REDIS_URI="${SESSION_REDIS_URI}" \
        --set SESSION_COOKIE_TTL="${SESSION_COOKIE_TTL}" \
        --set SESSION_SECRET="${SESSION_SECRET}" \
        --set LDAP_URL="${LDAP_URL}" \
        --set LDAP_BIND_DN="${LDAP_BIND_DN}" \
        --set LDAP_BIND_PW="${LDAP_BIND_PW}" \
        --set LDAP_SEARCH_BASE="${LDAP_SEARCH_BASE}" \
        --set LDAP_SEARCH_FILTER="${LDAP_SEARCH_FILTER}" \
        --set LDAP_SEARCH_GROUP="${LDAP_SEARCH_GROUP}" \
        --set LDAP_SEARCH_BASE_ALL_USERS="${LDAP_SEARCH_BASE_ALL_USERS}" \
        --set LDAP_SEARCH_FILTER_ALL_USERS="${LDAP_SEARCH_FILTER_ALL_USERS}" \
        --set LDAP_REDIS_URI="${LDAP_REDIS_URI}" \
        --set LDAP_REDIS_TTL="${LDAP_REDIS_TTL}" \
        --set MICROSERVICE_URL="${MICROSERVICE_URL}" \
        --set SOAP_URL="${SOAP_URL}" \
        --set SOAP_DOMAIN="${SOAP_DOMAIN}" \
        --set NEWS_URL="${NEWS_URL}" \
        --set NEWS_API_URL="${NEWS_API_URL}" \
        --set MAIL_URL="${MAIL_URL}" \
        --set MAIL_LOGIN_URL="${MAIL_LOGIN_URL}" \
        --set MEETING_URL="${MEETING_URL}" \
        --set image.repository="${CI_REGISTRY_IMAGE}" \
        --set image.tag="${CI_COMMIT_SHA}" \
        --install --namespace=${KUBE_NAMESPACE} \
        --debug --values helm/portal/values.yaml
    # Portal-sync
    - |
      helm upgrade ${CI_PROJECT_NAME}-sync helm/portal-sync \
        --install --namespace=${KUBE_NAMESPACE} \
        --debug --values helm/portal-sync/values.yaml \
        --set PORT="${PORT_MICROSERVICE}" \
        --set image.repository="${CI_REGISTRY_IMAGE}" \
        --set image.tag="${CI_COMMIT_SHA}"
