stages:
  - bundle
  - test
  - build
  # - deploy

default:
  image: node:10.16-buster
  services:
    - postgres:10
    - redis:latest

variables:
  POSTGRES_DB: portaldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VbNfGhRtY321
  
cache:
  paths:
    - node_modules/

bundle:
  stage: bundle
  script:
    - npm install -g yarn
    - yarn
    - yarn jwt:cert
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - yarn test

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
