image: node:12

stages:
  - bundle
  # - test
  # - build
  - deploy

services:
  - postgres:11.5
  - redis:5.0.5

bundle:
  stage: bundle
  script:
    # - uname -a
    # - env
    # - yarn
    - (! test -f /usr/local/bin/yarn) && npm install -g yarn
    - cp --remove-destination "${CI_ENVIRONMENT_VARIABLES}" .env
    - yarn jwt:cert
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    untracked: true
    policy: push
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
      - .env
      - jwt.public.pem
      - jwt.private.pem
    expire_in: 12 hours

# test:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn test -u

# build:
#   stage: build
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn build
#   artifacts:
#     paths:
#       - .nest/
#       - .next/
#     expire_in: 12 hours

deploy:
  image: docker:dind
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  script:
    - docker build -t portal .
    - docker run -d -p4000:4000 --name=portal portal
