stages:
  - bundle
  # - test
  # - build
  - production
  - deploy

variables:
  KUBECONFIG: /etc/kubernetes/kubelet.conf
  PRODUCTION_NAMESPACE: default
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2    

before_script:
  - cp --remove-destination "${ENVIRONMENT_VARIABLES}" .env
  - cp --remove-destination "${JWT_PRIVATE_PEM}" jwt.private.pem
  - cp --remove-destination "${JWT_PUBLIC_PEM}" jwt.public.pem

bundle:
  image: node:12-slim
  stage: bundle
  script:
    - (! test -f /usr/local/bin/yarn) && npm install -g yarn
    # - ls -la
    # - yarn
    # - ls -la
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    # untracked: true
    policy: pull-push
    paths:
      - node_modules/
  artifacts:
    paths:
      - .env
      - jwt.public.pem
      - jwt.private.pem
    expire_in: 12 hours

# test:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn test -u

# build:
#   stage: build
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn build
#   artifacts:
#     paths:
#       - .nest/
#       - .next/
#     expire_in: 12 hours

production:
  stage: production
  image: docker:latest
  services:
    - docker:dind
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    # untracked: true
    policy: pull-push
    paths:
      - /var/lib/docker
      - node_modules/
  script:
    - docker images
    - docker build --cache-from $CI_PROJECT_NAME:latest --tag $CI_PROJECT_NAME:$CI_COMMIT_SHA --tag $CI_PROJECT_NAME:latest .

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    # untracked: true
    policy: pull
    paths:
      - node_modules/
  before_script:
    # - mkdir -p /etc/deploy
    # - cp --remove-destination "${CI_KUBELET_CONFIG}" "${KUBECONFIG}"
    - helm init --client-only
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo update
    - kubectl get pods --all-namespaces
  script:
    - ls -la
    - ls -la /var/lib/docker
