stages:
  - bundle
  # - test
  # - build
  - deploy

# services:
#   - postgres:11.5
#   - redis:5.0.5

bundle:
  image: node:12
  stage: bundle
  script:
    - uname -a
    - env
    - (! test -f /usr/local/bin/yarn) && npm install -g yarn
    - cp --remove-destination "${CI_ENVIRONMENT_VARIABLES}" .env
    - yarn
    - yarn jwt:cert
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    untracked: true
    policy: push
    paths:
      - node_modules/
  artifacts:
    paths:
      # - node_modules/
      - .env
      - jwt.public.pem
      - jwt.private.pem
    expire_in: 12 hours

# test:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn test -u

# build:
#   stage: build
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     untracked: true
#     paths:
#       - node_modules/
#     policy: pull
#   script:
#     - (! test -f /usr/local/bin/yarn) && npm install -g yarn
#     - yarn build
#   artifacts:
#     paths:
#       - .nest/
#       - .next/
#     expire_in: 12 hours

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2    
  script:
    # - ls -la /run
    # - ls -la /var/lib/docker
    - docker build --cache-from $CI_PROJECT_NAME:latest --tag $CI_PROJECT_NAME:$CI_COMMIT_SHA --tag $CI_PROJECT_NAME:latest .
    - docker run -d -p4000:4000 --name=portal portal
