stages:
  - bundle
  - test
  - build
  - deploy

default:
  image: node:10.16-buster
  services:
    - postgres:10
    - redis:latest

variables:
  POSTGRES_DB: portaldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VbNfGhRtY321

cache:
  key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    untracked: true

before_script:
  - uname -a
  - npm install -g yarn
  - yarn

bundle:
  stage: bundle
  script:
    - yarn jwt:cert

test:
  stage: test
  script:
    - yarn test -u

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - .nest/
      - .next/

deploy:
  stage: deploy
  script:
    - echo TEST SUCCEDED

