stages:
  - bundle
  - test
  - build
  # - deploy

cache:
  paths:
    - node_modules/

bundle:
  image: node:latest
  stage: bundle
  script:
    - npm install -g yarn
    - yarn
    - yarn dev
  artifacts:
    paths:
      - node_modules/

test:
  image: node:alpine
  stage: test
  script:
    - npm install -g yarn
    - yarn
    - yarn test

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
