stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  PREFIX: ""
  RELEASE_NAME: ${PREFIX}${CI_PROJECT_NAME}
  RELEASE_NAME_SYNCH: ${PREFIX}${CI_PROJECT_NAME}-sync
  CONTAINER_IMAGE: ${PREFIX}${CI_PROJECT_NAME}:${CI_BUILD_REF}

prepare:
  image: node:13
  stage: build
  except:
    changes:
      - "*.md"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-build"
    paths:
      - node_modules/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=true

build_development:
  image: node:13
  stage: build
  environment:
    name: development
  except:
    changes:
      - "*.md"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-development"
    paths:
      - node_modules/
      - apps/portal/.next/cache/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=false
    - cd apps/portal && npx next telemetry status && npx next telemetry disable && cd ../..
    - ./entrypoint.sh test -u || true
    - time yarn build
    - time yarn build:sync
    - time yarn build:syncJob
  artifacts:
    paths:
      - .next/
      - dist
    expire_in: 16 hours

build_production:
  image: node:13
  stage: build
  environment:
    name: production
  except:
    changes:
      - "*.md"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-production"
    paths:
      - node_modules/
      - apps/portal/.next/cache/
  script:
    - env && echo -n "node version " && node -v
    - yarn install --production=false
    - cd apps/portal && npx next telemetry status && npx next telemetry disable && cd ../..
    - ./entrypoint.sh test -u || true
    - time yarn build
    - time yarn build:sync
    - time yarn build:syncJob
  artifacts:
    paths:
      - .next/
      - dist
    expire_in: 16 hours

docker:
  image: docker:latest
  stage: docker
  except:
    changes:
      - "*.md"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-build"
    paths:
      - node_modules/
    policy: pull
  script:
    - |
      \
      if [ ! -d "node_modules" ]; then echo '!! CACHE NOT EXIST !!'; exit SIGINT; fi
    # - docker login
    - docker build --tag ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${DOCKER_REGISTRY}/${CONTAINER_IMAGE}
    - docker push ${DOCKER_REGISTRY}/${CONTAINER_IMAGE}

helm_development:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  except:
    changes:
      - "*.md"
  environment:
    name: development
  dependencies: []
  allow_failure: false
  script:
    - env
    # Portal
    - |
      helm upgrade ${RELEASE_NAME} helm/portal \
        --install --namespace=${NAMESPACE} \
        --debug --values helm/portal/values.yaml \
        --set replicaCount="1" \
        --set service.nodePort="30400" \
        --set service.nodePort_debug="30401" \
        --set PORT="${PORT}" \
        --set PORT_SSL="${PORT_SSL}" \
        --set DOMAIN="${DOMAIN}" \
        --set LOGLEVEL="${LOGLEVEL}" \        
        --set DATABASE_URI="${DATABASE_URI}" \
        --set DATABASE_URI_RD="${DATABASE_URI_RD}" \
        --set DATABASE_SCHEMA="${DATABASE_SCHEMA}" \
        --set DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}" \
        --set DATABASE_DROP_SCHEMA="${DATABASE_DROP_SCHEMA}" \
        --set DATABASE_MIGRATIONS_RUN="${DATABASE_MIGRATIONS_RUN}" \
        --set DATABASE_LOGGING="${DATABASE_LOGGING}" \
        --set DATABASE_REDIS_URI="${DATABASE_REDIS_URI}" \
        --set DATABASE_REDIS_TTL="${DATABASE_REDIS_TTL}" \
        --set HTTP_REDIS_URI="${HTTP_REDIS_URI}" \
        --set HTTP_REDIS_TTL="${HTTP_REDIS_TTL}" \
        --set HTTP_REDIS_MAX_OBJECTS="${HTTP_REDIS_MAX_OBJECTS}" \
        --set SESSION_NAME="${SESSION_NAME}" \
        --set SESSION_REDIS_URI="${SESSION_REDIS_URI}" \
        --set SESSION_COOKIE_TTL="${SESSION_COOKIE_TTL}" \
        --set SESSION_SECRET="${SESSION_SECRET}" \
        --set LDAP_URL="${LDAP_URL}" \
        --set LDAP_BIND_DN="${LDAP_BIND_DN}" \
        --set LDAP_BIND_PW="${LDAP_BIND_PW}" \
        --set LDAP_SEARCH_BASE="${LDAP_SEARCH_BASE}" \
        --set LDAP_SEARCH_FILTER="${LDAP_SEARCH_FILTER}" \
        --set LDAP_SEARCH_GROUP="${LDAP_SEARCH_GROUP}" \
        --set LDAP_SEARCH_BASE_ALL_USERS="${LDAP_SEARCH_BASE_ALL_USERS}" \
        --set LDAP_SEARCH_FILTER_ALL_USERS="${LDAP_SEARCH_FILTER_ALL_USERS}" \
        --set LDAP_REDIS_URI="${LDAP_REDIS_URI}" \
        --set LDAP_REDIS_TTL="${LDAP_REDIS_TTL}" \
        --set MICROSERVICE_URL="${MICROSERVICE_URL}" \
        --set SOAP_URL="${SOAP_URL}" \
        --set SOAP_DOMAIN="${SOAP_DOMAIN}" \
        --set NEWS_URL="${NEWS_URL}" \
        --set NEWS_API_URL="${NEWS_API_URL}" \
        --set MAIL_URL="${MAIL_URL}" \
        --set MAIL_LOGIN_URL="${MAIL_LOGIN_URL}" \
        --set MEETING_URL="${MEETING_URL}" \
        --set image.repository="${DOCKER_REGISTRY}/${RELEASE_NAME}" \
        --set image.tag="${CI_BUILD_REF}"
    # Portal-sync
    - |
      helm upgrade ${RELEASE_NAME_SYNCH} helm/portal-sync \
        --install --namespace=${NAMESPACE} \
        --debug --values helm/portal-sync/values.yaml \
        --set replicaCount="1" \
        --set PORT="${PORT_MICROSERVICE}" \
        --set image.repository="${DOCKER_REGISTRY}/${RELEASE_NAME}" \
        --set image.tag="${CI_BUILD_REF}"

helm_production:
  image: dtzar/helm-kubectl:latest
  stage: deploy
  except:
    changes:
      - "*.md"
  environment:
    name: production
  dependencies: []
  when: manual
  allow_failure: false
  script:
    - env
    # Portal
    - |
      helm upgrade ${RELEASE_NAME} helm/portal \
        --install --namespace=${NAMESPACE} \
        --debug --values helm/portal/values.yaml \
        --set service.nodePort="30300" \
        --set service.nodePort_debug="30301" \
        --set PORT="${PORT}" \
        --set PORT_SSL="${PORT_SSL}" \
        --set DOMAIN="${DOMAIN}" \
        --set LOGLEVEL="${LOGLEVEL}" \        
        --set DATABASE_URI="${DATABASE_URI}" \
        --set DATABASE_URI_RD="${DATABASE_URI_RD}" \
        --set DATABASE_SCHEMA="${DATABASE_SCHEMA}" \
        --set DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}" \
        --set DATABASE_DROP_SCHEMA="${DATABASE_DROP_SCHEMA}" \
        --set DATABASE_MIGRATIONS_RUN="${DATABASE_MIGRATIONS_RUN}" \
        --set DATABASE_LOGGING="${DATABASE_LOGGING}" \
        --set DATABASE_REDIS_URI="${DATABASE_REDIS_URI}" \
        --set DATABASE_REDIS_TTL="${DATABASE_REDIS_TTL}" \
        --set HTTP_REDIS_URI="${HTTP_REDIS_URI}" \
        --set HTTP_REDIS_TTL="${HTTP_REDIS_TTL}" \
        --set HTTP_REDIS_MAX_OBJECTS="${HTTP_REDIS_MAX_OBJECTS}" \
        --set SESSION_NAME="${SESSION_NAME}" \
        --set SESSION_REDIS_URI="${SESSION_REDIS_URI}" \
        --set SESSION_COOKIE_TTL="${SESSION_COOKIE_TTL}" \
        --set SESSION_SECRET="${SESSION_SECRET}" \
        --set LDAP_URL="${LDAP_URL}" \
        --set LDAP_BIND_DN="${LDAP_BIND_DN}" \
        --set LDAP_BIND_PW="${LDAP_BIND_PW}" \
        --set LDAP_SEARCH_BASE="${LDAP_SEARCH_BASE}" \
        --set LDAP_SEARCH_FILTER="${LDAP_SEARCH_FILTER}" \
        --set LDAP_SEARCH_GROUP="${LDAP_SEARCH_GROUP}" \
        --set LDAP_SEARCH_BASE_ALL_USERS="${LDAP_SEARCH_BASE_ALL_USERS}" \
        --set LDAP_SEARCH_FILTER_ALL_USERS="${LDAP_SEARCH_FILTER_ALL_USERS}" \
        --set LDAP_REDIS_URI="${LDAP_REDIS_URI}" \
        --set LDAP_REDIS_TTL="${LDAP_REDIS_TTL}" \
        --set MICROSERVICE_URL="${MICROSERVICE_URL}" \
        --set SOAP_URL="${SOAP_URL}" \
        --set SOAP_DOMAIN="${SOAP_DOMAIN}" \
        --set NEWS_URL="${NEWS_URL}" \
        --set NEWS_API_URL="${NEWS_API_URL}" \
        --set MAIL_URL="${MAIL_URL}" \
        --set MAIL_LOGIN_URL="${MAIL_LOGIN_URL}" \
        --set MEETING_URL="${MEETING_URL}" \
        --set image.repository="${DOCKER_REGISTRY}/${RELEASE_NAME}" \
        --set image.tag="${CI_BUILD_REF}"
    # Portal-sync
    - |
      helm upgrade ${RELEASE_NAME_SYNCH} helm/portal-sync \
        --install --namespace=${NAMESPACE} \
        --debug --values helm/portal-sync/values.yaml \
        --set PORT="${PORT_MICROSERVICE}" \
        --set image.repository="${DOCKER_REGISTRY}/${RELEASE_NAME}" \
        --set image.tag="${CI_BUILD_REF}"
