stages:
  - bundle
  # - test
  # - build
  - production
  - deploy

variables:
  KUBECONFIG: /etc/kubernetes/kubelet.conf
  PRODUCTION_NAMESPACE: default
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2    

bundle:
  image: node:12
  stage: bundle
  script:
    - cp --remove-destination "${ENVIRONMENT_VARIABLES}" .env
    - cp --remove-destination "${JWT_PRIVATE_PEM}" jwt.private.pem
    - cp --remove-destination "${JWT_PUBLIC_PEM}" jwt.public.pem
    # - yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    policy: pull-push
    paths:
      - node_modules/
  artifacts:
    paths:
      - .env
      - jwt.public.pem
      - jwt.private.pem
    expire_in: 12 hours

# test:
#   image: node:12
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     policy: pull
#     paths:
#       - node_modules/
#   script:
#     - yarn test -u

# build:
#   image: node:12
#   stage: build
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
#     policy: pull
#     paths:
#       - node_modules/
#   script:
#     - yarn build
#   artifacts:
#     paths:
#       - .nest/
#       - .next/
#     expire_in: 12 hours

production:
  stage: production
  image: docker:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    policy: pull
    paths:
      - node_modules/
  script:
    - docker images $CI_PROJECT_NAME
    - docker image rm $CI_PROJECT_NAME:latest
    - docker build --cache-from $CI_PROJECT_NAME:latest --tag $CI_PROJECT_NAME:$CI_COMMIT_SHA --tag $CI_PROJECT_NAME:latest .
    - docker images $CI_PROJECT_NAME

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_PATH_SLUG}
    policy: pull
    paths:
      - node_modules/
  before_script:
    - helm init --client-only
    - helm repo update
    - kubectl get pods --all-namespaces
    - helm install --name=kngk-portal --debug helm/kngk-portal
  script:
    - ls -la
    - ls -la /var/lib/docker
