image: node:10.16-buster

stages:
  - bundle
  - test
  - build
  - deploy

services:
  - postgres:10
  - redis:latest

variables:
  POSTGRES_DB: portaldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VbNfGhRtY321

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
  untracked: true
  paths:
    - node_modules/

before_script:
  - uname -a
  # - env
  - ls -l /cache
  - npm install -g yarn

bundle:
  stage: bundle
  script:
    - ls -l
    - yarn
    - yarn jwt:cert
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
    untracked: true
    paths:
      - node_modules/
  artifacts:
    paths:
      - jwt.public.pem
      - jwt.private.pem

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  script:
    - ls -l
    - yarn test -u

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  script:
    - ls -l
    - yarn build
    - ls -l
  artifacts:
    paths:
      - .nest/
      - .next/

deploy:
  stage: deploy
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_DIR}
    untracked: true
    paths:
      - node_modules/
    policy: pull
  script:
    - ls -l
    - echo TEST SUCCEDED
