stages:
  - test
  - build
  - deploy

default:
  image: node:10.16-buster
  services:
    - postgres:10
    - redis:latest
  before_script:
    - uname -a
    - npm install -g yarn
    - yarn
    - yarn jwt:cert

variables:
  POSTGRES_DB: portaldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VbNfGhRtY321

cache:
  paths:
    - node_modules/
  untracked: true

test:
  stage: test
  script:
    - yarn test -u

build:
  stage: build
  script:
    - yarn build

deploy:
  stage: deploy
  script:
    - docker

