image: node:10.16-buster

stages:
  - bundle
  - test
  - build
  - deploy

services:
  - postgres:10
  - redis:latest

variables:
  POSTGRES_DB: portaldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: VbNfGhRtY321

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  untracked: true
  policy: pull-push

before_script:
  - uname -a
  - env
  - npm install -g yarn
  - ls -l
  - yarn

bundle:
  stage: bundle
  script:
    - ls -l
    - yarn jwt:cert
  artifacts:
    paths:
      - jwt.public.pem
      - jwt.private.pem

test:
  stage: test
  script:
    - ls -l
    - yarn test -u

build:
  stage: build
  script:
    - ls -l
    - yarn build
  artifacts:
    paths:
      - .nest/
      - .next/

deploy:
  stage: deploy
  script:
    - ls -l
    - echo TEST SUCCEDED

