apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
{{ include "portal.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  # https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "portal.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.image.tag }}
    spec:
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["tail", "-f", "/var/log/faillog"]
          ports:
            - name: microsvc
              containerPort: {{ .Values.PORT }}
              protocol: TCP
            {{- if .Values.PORT_DEBUG }}
            - name: http-debug
              containerPort: {{ .Values.PORT_DEBUG }}
              protocol: TCP
            {{- end }}
          env:
            - name: PORT
              value: {{ .Values.PORT | quote }}
            {{- if .Values.PORT_DEBUG }}
            - name: PORT_DEBUG
              value: {{ .Values.PORT_DEBUG | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configmap
              mountPath: /portal/.local
            - name: portal-tmp
              mountPath: /portal/public/tmp
      volumes:
        - name: portal-tmp
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: configmap
          configMap:
            name: portal-configmap
            items:
              - key: env
                path: .env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
