apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "portal.fullname" . }}-job
  labels:
{{ include "portal.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.signatureShedule | quote }}
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.imageCredentials.enabled }}
          imagePullSecrets:
          - name: {{ .Values.imageCredentials.name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ["start:syncJob"]
              ports:
                - name: microsvc
                  containerPort: {{ .Values.PORT | default 4222 }}
                  protocol: TCP
                {{- if .Values.PORT_DEBUG }}
                - name: http-debug
                  containerPort: {{ .Values.PORT_DEBUG }}
                  protocol: TCP
                {{- end }}
              env:
                - name: PORT
                  value: {{ .Values.PORT | quote }}
                {{- if .Values.PORT_DEBUG }}
                - name: http_debug
                  value: {{ .Values.PORT_DEBUG | quote }}
                {{- end }}
              volumeMounts:
                - name: configmap
                  mountPath: /portal/.local
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: Never
          volumes:
            - name: configmap
              configMap:
                name: portal-configmap
                items:
                  - key: env
                    path: .env
