# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: docker.kube.i-npz.ru/portal
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "portal"
fullnameOverride: "portal"

# App
HOST: 0.0.0.0
PORT: 4000
PORT_DEBUGGER: 9229

# DB
DATABASE_CONNECTION: "postgres"
DATABASE_HOST: "postgresql.default.svc.cluster.local"
DATABASE_PORT: 5432
DATABASE_USERNAME: "postgres"
DATABASE_PASSWORD: ""
DATABASE_DATABASE: "portaldb"
DATABASE_SCHEMA: "public"
DATABASE_SYNCHRONIZE: "true"
DATABASE_DROP_SCHEMA: "true"
DATABASE_MIGRATIONS_RUN: "true"
DATABASE_LOGGING: "true"
DATABASE_CACHE: "true"
# DB Redis
DATABASE_REDIS_HOST: "redis.default.svc.cluster.local"
DATABASE_REDIS_PORT: 6379
DATABASE_REDIS_PASSWORD: ""
DATABASE_REDIS_TTL: 300
DATABASE_REDIS_DB: 0

# HTTP Redis
HTTP_REDIS_HOST: "redis.default.svc.cluster.local"
HTTP_REDIS_PORT: 6379
HTTP_REDIS_DB: 1
HTTP_REDIS_PASSWORD: ""
HTTP_REDIS_TTL: 300
HTTP_REDIS_MAX_OBJECTS: 10000
HTTP_REDIS_PREFIX: ""

# Session Redis
SESSION_REDIS_HOST: "redis.default.svc.cluster.local"
SESSION_REDIS_PORT: 6379
SESSION_REDIS_DB: 2
SESSION_REDIS_PASSWORD: ""
SESSION_COOKIE_TTL: 300
SESSION_SECRET: "supersecret"

# LDAP
LDAP_URL: "ldap://activedirectory:389"
LDAP_BIND_DN: "CN=user,DC=example,DC=local"
LDAP_BIND_PW: ""
LDAP_SEARCH_BASE: "DC=example,DC=local"
LDAP_SEARCH_FILTER: "(sAMAccountName={{username}})"
LDAP_SEARCH_GROUP: "(&(objectClass=group)(member={{dn}}))"
LDAP_SEARCH_BASE_ALL_USERS: "DC=example,DC=local"
LDAP_SEARCH_FILTER_ALL_USERS: "(&(&(|(&(objectClass=user)(objectCategory=person))(&(objectClass=contact)(objectCategory=person)))))"
# LDAP Redis
LDAP_REDIS_HOST: "redis.default.svc.cluster.local"
LDAP_REDIS_PORT: 6379
LDAP_REDIS_DB: 2
LDAP_REDIS_PASSWORD: ""
LDAP_REDIS_TTL: 300

MICROSERVICE_URL: "nats://nats-cluster.nats-io:4222"
MICROSERVICE_USER: "admin"
MICROSERVICE_PASS: "supersecret"

SOAP_URL: "https://soap1c"
SOAP_USER: "admin"
SOAP_PASS: "supersecret"

NEWS_URL: "https://news"
NEWS_API_URL: "https://news/api"

MAIL_URL: "/roundcube/"
MAIL_LOGIN_URL: "https://roundcube.production/login/index.php"

MEETING_URL: "https://meeting"

service:
  type: LoadBalancer

  nodePort: 30300
  nodePort_debugger: 30301

  externalIPs:
    - 10.10.5.70
    - 10.10.5.71

tls:
  enabled: false

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: portal.production.svc.cluster.local
      paths: []

  tls: []
  #  - secretNamls e: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Liveness and Readiness probe values.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 650m
    memory: 1Gi
  requests:
    cpu: 650m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
