# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-registry.mycompany.com/portal
  tag: latest
  pullPolicy: Always

imageCredentials:
  enabled: true
  name: portal-sync-registry
  registry: docker-registry.mycompany.com
  username: docker-reg-user
  password: XXXXXXXXXXXX

nameOverride: "portal-tasks"
fullnameOverride: "portal-tasks"

# App
PORT: 4222

service:
  type: ClusterIP

tls:
  enabled: false

## Liveness and Readiness probe values.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 500m
  #  memory: 4Gi
  #requests:
  #  cpu: 250m
  #  memory: 2Gi
  #  ephemeral-storage: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
