apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{ include "portal.labels" . | indent 4 }}
data:
  # NODE_ENV: {{ .Values.NODE_ENV | default "production" | quote }}

  HOST: {{ .Values.HOST | default "localhost" | quote }}
  PORT: {{ .Values.PORT | default "4000" | quote }}

  # PORT_DEBUGGER: {{ .Values.PORT_DEBUGGER | default "9229" | quote }}

  DATABASE_CONNECTION: {{ .Values.DATABASE_CONNECTION | default "postgres" | quote }}
  DATABASE_HOST: {{ .Values.DATABASE_HOST | default "localhost" | quote }}
  DATABASE_PORT: {{ .Values.DATABASE_PORT | default "5432" | quote }}
  DATABASE_USERNAME: {{ .Values.DATABASE_USERNAME | default "postgres" | quote }}
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD | default "supersecret" | quote }}
  DATABASE_DATABASE: {{ .Values.DATABASE_DATABASE | default "postgres" | quote }}
  DATABASE_SCHEMA: {{ .Values.DATABASE_SCHEMA | default "public" | quote }}
  DATABASE_SYNCHRONIZE: {{ .Values.DATABASE_SYNCHRONIZE | default "true" | quote }}
  DATABASE_DROP_SCHEMA: {{ .Values.DATABASE_DROP_SCHEMA | default "true" | quote }}
  DATABASE_MIGRATIONS_RUN: {{ .Values.DATABASE_MIGRATIONS_RUN | default "true" | quote }}
  DATABASE_LOGGING: {{ .Values.DATABASE_LOGGING | default "true" | quote }}
  DATABASE_CACHE: {{ .Values.DATABASE_CACHE | default "true" | quote }}

  # LDAP Redis
  LDAP_REDIS_HOST: {{ .Values.LDAP_REDIS_HOST | default "localhost" | quote }}
  LDAP_REDIS_PORT: {{ .Values.LDAP_REDIS_PORT | default "6379" | quote }}
  LDAP_REDIS_DB: {{ .Values.LDAP_REDIS_DB | default "0" | quote }}
  LDAP_REDIS_PASSWORD: {{ .Values.LDAP_REDIS_PASSWORD | default "" | quote }}
  LDAP_REDIS_TTL: {{ .Values.LDAP_REDIS_TTL | default "300" | quote }}

  # HTTP Redis
  HTTP_REDIS_HOST: {{ .Values.HTTP_REDIS_HOST | default "localhost" | quote }}
  HTTP_REDIS_PORT: {{ .Values.HTTP_REDIS_PORT | default "6379" | quote }}
  HTTP_REDIS_DB: {{ .Values.HTTP_REDIS_DB | default "2" | quote }}
  HTTP_REDIS_PASSWORD: {{ .Values.HTTP_REDIS_PASSWORD | default "" | quote }}
  HTTP_REDIS_TTL: {{ .Values.HTTP_REDIS_TTL | default "60" | quote }}
  HTTP_REDIS_MAX_OBJECTS: {{ .Values.HTTP_REDIS_MAX_OBJECTS | default "10000" | quote }}
  HTTP_REDIS_PREFIX: {{ .Values.REDIS_PREFIX | default "" | quote }}

  LDAP_URL: {{ .Values.LDAP_URL | default "ldap://activedirectory:389" | quote }}
  LDAP_BIND_DN: {{ .Values.LDAP_BIND_DN | default "CN=user,DC=example,DC=local" | quote }}
  LDAP_BIND_PW: {{ .Values.LDAP_BIND_PW | default "supersecret" | quote }}
  LDAP_SEARCH_BASE: {{ .Values.LDAP_SEARCH_BASE | default "DC=example,DC=local" | quote }}
  LDAP_SEARCH_FILTER: {{ .Values.LDAP_SEARCH_FILTER | default "(sAMAccountName={{username}})" | quote }}
  LDAP_SEARCH_BASE_ALL_USERS: {{ .Values.LDAP_SEARCH_BASE_ALL_USERS | default "DC=example,DC=local" | quote }}
  LDAP_SEARCH_FILTER_ALL_USERS: {{ .Values.LDAP_SEARCH_FILTER_ALL_USERS | default "(&(&(|(&(objectClass=user)(objectCategory=person))(&(objectClass=contact)(objectCategory=person)))))" | quote }}
