apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
{{ include "portal.labels" . | indent 4 }}
    app_name: {{ .Values.image.repository }}:{{ .Values.image.tag }}
{{- if .Chart.AppVersion }}
    chart_version: {{ .Chart.AppVersion | quote }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.PORT | default 4000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{ else }}
              scheme: HTTP
              {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{- end }}
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: NODE_ENV
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: PORT
            - name: PORT_DEBUGGER
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: PORT_DEBUGGER
            - name: DATABASE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_CONNECTION
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_PORT
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_PASSWORD
            - name: DATABASE_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_DATABASE
            - name: DATABASE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_SCHEMA
            - name: DATABASE_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_SYNCHRONIZE
            - name: DATABASE_DROP_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_DROP_SCHEMA
            - name: DATABASE_MIGRATIONS_RUN
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_MIGRATIONS_RUN
            - name: DATABASE_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_LOGGING
            - name: DATABASE_CACHE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_CACHE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: REDIS_DB
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: REDIS_PASSWORD
            - name: REDIS_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: REDIS_PREFIX
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SESSION_SECRET
            - name: LDAP_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_URL
            - name: LDAP_BIND_DN
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_BIND_DN
            - name: LDAP_BIND_PW
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_BIND_PW
            - name: LDAP_SEARCH_BASE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_BASE
            - name: LDAP_SEARCH_FILTER
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_FILTER
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
