apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
{{ include "portal.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "portal.name" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.image.tag }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.PORT | default 4000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{ else }}
              scheme: HTTP
              {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              {{- if .Values.tls.enabled }}
              scheme: HTTPS
              {{ else }}
              scheme: HTTP
              {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: PORT
              value: {{ .Values.PORT | default "4000" | quote }}
            - name: PORT_DEBUG
              value: {{ .Values.PORT_DEBUG | default "9229" | quote }}
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_URI
            - name: DATABASE_URI_RD
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_URI_RD
            - name: DATABASE_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_SCHEMA
            - name: DATABASE_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_SYNCHRONIZE
            - name: DATABASE_DROP_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_DROP_SCHEMA
            - name: DATABASE_MIGRATIONS_RUN
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_MIGRATIONS_RUN
            - name: DATABASE_LOGGING
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_LOGGING
            - name: DATABASE_REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_REDIS_URI
            - name: DATABASE_REDIS_TTL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: DATABASE_REDIS_TTL
            # HTTP
            - name: HTTP_REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: HTTP_REDIS_URI
            - name: HTTP_REDIS_TTL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: HTTP_REDIS_TTL
            - name: HTTP_REDIS_MAX_OBJECTS
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: HTTP_REDIS_MAX_OBJECTS
            # Session
            - name: SESSION_REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SESSION_REDIS_URI
            - name: SESSION_COOKIE_TTL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SESSION_COOKIE_TTL
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SESSION_SECRET
            # LDAP
            - name: LDAP_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_URL
            - name: LDAP_BIND_DN
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_BIND_DN
            - name: LDAP_BIND_PW
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_BIND_PW
            - name: LDAP_SEARCH_BASE
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_BASE
            - name: LDAP_SEARCH_FILTER
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_FILTER
            - name: LDAP_SEARCH_GROUP
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_GROUP
            - name: LDAP_SEARCH_BASE_ALL_USERS
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_BASE_ALL_USERS
            - name: LDAP_SEARCH_FILTER_ALL_USERS
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_SEARCH_FILTER_ALL_USERS
            # LDAP Redis
            - name: LDAP_REDIS_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_REDIS_URI
            - name: LDAP_REDIS_TTL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: LDAP_REDIS_TTL
            - name: MICROSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: MICROSERVICE_URL
            - name: SOAP_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SOAP_URL
            - name: SOAP_USER
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SOAP_USER
            - name: SOAP_PASS
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: SOAP_PASS
            - name: NEWS_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: NEWS_URL
            - name: NEWS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: NEWS_API_URL
            - name: MAIL_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: MAIL_URL
            - name: MAIL_LOGIN_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: MAIL_LOGIN_URL
            - name: MEETING_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-configmap
                  key: MEETING_URL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
