apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
{{ include "portal.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "portal.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     {{- if .Values.tls.enabled }}
          #     scheme: HTTPS
          #     {{ else }}
          #     scheme: HTTP
          #     {{- end }}
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.livenessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # readinessProbe:
          #   httpGet:
          #     {{- if .Values.tls.enabled }}
          #     scheme: HTTPS
          #     {{- end }}
          #     path: /
          #     port: http
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          #   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          #   successThreshold: {{ .Values.readinessProbe.successThreshold }}
          #   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: NODE_ENV
              value: production
            - name: HOST
              value: {{ .Values.default.HOST }}
            - name: PORT
              value: {{ .Values.default.PORT }}
            - name: PORT_DEBUG
              value: {{ .Values.default.PORT_DEBUG }}
            - name: DATABASE_CONNECTION
              value: {{ .Values.default.DATABASE_CONNECTION }}
            - name: DATABASE_HOST
              value: {{ .Values.default.DATABASE_HOST }}
            - name: DATABASE_PORT
              value: {{ .Values.default.DATABASE_PORT }}
            - name: DATABASE_USERNAME
              value: {{ .Values.default.DATABASE_USERNAME }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.default.DATABASE_PASSWORD }}
            - name: DATABASE_DATABASE
              value: {{ .Values.default.DATABASE_DATABASE }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.default.DATABASE_SCHEMA }}
            - name: DATABASE_SYNCHRONIZE
              value: {{ .Values.default.DATABASE_SYNCHRONIZE }}
            - name: DATABASE_DROP_SCHEMA
              value: {{ .Values.default.DATABASE_DROP_SCHEMA }}
            - name: DATABASE_MIGRATIONS_RUN
              value: {{ .Values.default.DATABASE_MIGRATIONS_RUN }}
            - name: DATABASE_LOGGING
              value: {{ .Values.default.DATABASE_LOGGING }}
            - name: DATABASE_CACHE
              value: {{ .Values.default.DATABASE_CACHE }}
            - name: REDIS_HOST
              value: {{ .Values.default.REDIS_HOST }}
            - name: REDIS_PORT
              value: {{ .Values.default.REDIS_PORT }}
            - name: REDIS_DB
              value: {{ .Values.default.REDIS_DB }}
            - name: REDIS_PASSWORD
              value: {{ .Values.default.REDIS_PASSWORD }}
            - name: REDIS_PREFIX
              value: {{ .Values.default.REDIS_PREFIX }}
            - name: SESSION_SECRET
              value: {{ .Values.default.SESSION_SECRET }}
            - name: LDAP_URL
              value: {{ .Values.default.LDAP_URL }}
            - name: LDAP_BIND_DN
              value: {{ .Values.default.LDAP_BIND_DN }}
            - name: LDAP_BIND_PW
              value: {{ .Values.default.LDAP_BIND_PW }}
            - name: LDAP_SEARCH_BASE
              value: {{ .Values.default.LDAP_SEARCH_BASE }}
            - name: LDAP_SEARCH_FILTER
              value: {{ .Values.default.LDAP_SEARCH_FILTER }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
